---
title: "Using Linux Kernel Runtime Guard (LKRG)"
permalink: lkrg/
---

 - Installation of [**LKRG**](http://openwall.info/wiki/p_lkrg/Protected_Features) is exactly the same as loading normal kernel module. 
 - As soon as system is installed it starts the work. 
 - If default logging level is used, LKRG produces one short sentence saying that system is clean unless corruptions are detected.

```bash

# modinfo lkrg

filename:       /lib/modules/5.0.1-dragon-westmere/kernel/drivers/staging/lkrg/lkrg.ko
version:        0.6a-dragon
license:        GPL v2
description:    pi3s Linux kernel Runtime Guard
author:         Adam 'pi3' Zabrocki (http://pi3.com.pl)
srcversion:     000000000000000000000
depends:
staging:        Y
retpoline:      Y
intree:         Y
name:           lkrg
vermagic:       5.0.1-dragon-westmere SMP mod_unload 
sig_id:         PKCS#7
signer:
sig_key:
sig_hashalgo:   md4
signature:
parm:           p_init_log_level:Logging level init value [1 (alive) is default] (uint)

```

 - Install LKRG service:

[Download](https://drive.google.com/open?id=1P6Vsd_snlSfpoyr0msZgL5dhJYGp7XmS) install scripts, unpack and run scripts:

```
$ tar zxf install_lkrg-service.tar.gz

$ lkrg-systemd install

Uninstall service run:

$ lkrg-systemd uninstall

``` 

 View status service - **$ systemctl status lkrg.service** 


 - The project has built in a **sysctl** interface which enables the interaction between the administrator and LKRG.
 
 **By default 5 different options are available:**

```bash
 # sysctl -a | egrep lkrg
 
lkrg.block_modules = 0
lkrg.ci_panic = 0
lkrg.clean_message = 1
lkrg.force_run = 0
lkrg.hide = 0
lkrg.log_level = 1
lkrg.random_events = 1
lkrg.timestamp = 15
lkrg.smep_panic = 1
lkrg.umh_lock = 0
```

 - Blocking module functionality (lkrg.block_modules) - only two options are
    available:
        0 - do NOT lock the kernel and allow to load kernel module
        1 - lock the kernel and do NOT allow to load kernel module

 - Kernel panic on CI failure (lkrg.ci_panic) - only two options are
    available:
        0 - do NOT crash the kernel on CI failure (default)
        1 - crash the kernel (call panic()) on CI failure

 - Printing "System is clean!" message (lkrg.clean_message) - only two options
    are available:
        0 - do NOT print "System is clean!" message regardless of log_level
            value
        1 - if log_level value allows it, print "System is clean!" message

 - Force (lkrg.force_run) - forces LKRG to run integrity function right now.
    It is always visible as 0 number. Nevertheless, if you set it to 1, the
    integrity checking function will be immediately fired and value restored to
    0 again

 - log level (lkrg.log_level) - it might be a number between 0-4 or 0-6 (if
    debugging compilation was used). A strong debug provides very useful data
    to identify where could be a specific problem with LKRG (if it ever
    appears). Unfortunately, it produces tons of logs per execution and must be
    used only for debugging purpose, not as a normal run.
    
 - Random events (lkrg.random_events) - only two options are available:
    0 - do NOT perform integrity checking on the random events (perform it
        only at regular intervals configured by lkrg.timestamp)
    1 - perform integrity checking on the random events (as well as at the
        regular intervals)

 - timestamp (lkrg.timestamp) - changes how often kernel timer will be
    launched (kernel timer periodically calls integrity function). It can't be
    less than 5 seconds (not to eat too much system resources) and not more
    than 1800 seconds (half an hour) - not to be silent for too long

 - sysctl interface (lkrg.smep_panic) which will be enabled by default. 
    If LKRG detects SMEP violation it will kill the kernel 
    (invoke function panic()). This mitigation should be enough to stop bypasses 
    but it is only effective on machines which support SMEP

 - sysctl interface (lkrg.umh_lock) which will be disabled by default. 
    If it is enabled, LKRG completely locks down 
    UMH functionality, and nothing can be executed via this interface. It has of 
    course side effects e.g. systemd daemon is using UMH to invoke 
    "systemd-cgroups-agent". If you enable lkrg.umh_lock then any call to the 
    systemd-cgroups-agent will fail. However, not all systems are using systemd. 
    Additionally, if you're super paranoid this feature can be useful for you.


---

